### ISSUE TITLE
Deepvariant error with SLmapped Workflow

### ISSUE THREAD

**Issue by Sami-St** [PacificBiosciences/HiFiTargetEnrichment#4]
Hey everyone,
i am trying to run the SLmapped workflow but i cant get past the deepvariant job.
[Slurm-log.txt](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11969007/Slurm-log.txt)

There where a few ideas like putting sleep commands in the Rules and so on but sadly nothing is working, my only other idea on why its not working is that i am running tensorflow with my CPU cause the machine dosent have a GPU to work with.

P.s. if you need additonal information or something just tell me, kinda new to github and this is my first Issue.

many thanks in advance

**Comment by MeHelmy** [comment]
Hi @Sami-St,

Thank you for reaching out. Upon reviewing the log file, I noticed the error message `sbatch: error: Batch job submission failed: Invalid feature specification`. This suggests that you are attempting to submit a job with incorrect configurations.

To resolve this issue, please ensure that you have correctly modified the `partition` in the `cluster.yaml` configuration file to match your specific partition name.

Regarding the mention of GPU, it is required at a different stage of the workflow, not in the current part.

If you have any further questions or concerns, please don't hesitate to ask.

Best regards,
Medhat

**Comment by Sami-St** [comment]
Hey @MeHelmy,

Thanks for the quick reply, i also thought of that, the partition name is compute so this should be fine... i think
[Cluster.txt](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11969334/Cluster.txt)
[Cluster-config.txt](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11969386/Cluster-config.txt)

**Comment by Sami-St** [comment]
Even if this is not the problem atm is the GPU later on a must or is there anyway to avoid it and switch it to CPU (not that important of a question just need to know before i upgrade)

**Comment by MeHelmy** [comment]
Hmm, could you please share the file `batches/Test30/logs/deepvariant/make_examples/D18757.hs37d5.00009-of-00096.log` with me? Regarding GPUs, DeepVariant can indeed run on CPUs, but it may take slightly longer to complete the process.

**Comment by Sami-St** [comment]
Sure thing it probably wont help tho because its empty like all of them...
[D18757.hs37d5.00009-of-00096.log](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11969697/D18757.hs37d5.00009-of-00096.log)
And thats good to know thanks.

**Comment by MeHelmy** [comment]
It makes sense that the file is empty because the cluster submission failed right from the beginning. We should focus on troubleshooting the cluster submission issue to ensure the job can run successfully.

**Comment by Sami-St** [comment]
Sound like a plan, tho there isn't much i can think of that could be the problem except that my slurm setup is locally so i am compute node and controller at the same time maybe that is an issuse but if that would be the case pbsv call would also have a error wich it dosent.

It runs with Ubuntu 20.04.6, deepvariant in a docker container. And slurm didnt go into drain state so i think Memory shouldn't be an issue.

There shouldn't be an Issue with to many jobs or something since i put a 3min sleep in the shell commands and we also have lockfile.

The config files are above but if i missed something i can freely send it over.

**Comment by Sami-St** [comment]
sudo sbatch workflow/run_snakemake_SLmapped.sh Test30 ok Target_bases_covered_by_probes_ZK_LongRead_1vs1_0p1X_LRTE-93675747_hg19_220822113755.bed [Target_bases_covered_by_probes_ZK_LongRead_1vs1_0p1X_LRTE-93675747_hg19_220822113755.bed]

this is my starting command with "ok" being the folder with with the bam and bam.bai files.

I also did this without sudo but there wasn't any change 

edit: above i copyed the old slurm.config file (where i made mistakes) that was on my Windows desktop here is the one currently running 

[Cluster-config.txt](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11970228/Cluster-config.txt)

**Comment by jrharting** [comment]
To avoid the GPU requirement, make sure all "extra" parameters for deepvariant calls are set to nothing or commented out.  It looks like you have one remaining:

> deepvariant_postprocess_variants:
>   cpus: 4
>   extra: '--constraint=avx512'   <------- right here

**Comment by Sami-St** [comment]
Thanks for the info i removed it and tryed again seems like it did somethin i got a few new error's sadly 

[slurm-snakejob.deepvariant_make_examples.9.sh-5213-dev-srv-lab-cli.txt](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11984114/slurm-snakejob.deepvariant_make_examples.9.sh-5213-dev-srv-lab-cli.txt)
[slurm-run_snakemake_SLmapped.sh-5192-dev-srv-lab-cli.txt](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11984115/slurm-run_snakemake_SLmapped.sh-5192-dev-srv-lab-cli.txt)
[D18757.hs37d5.00009-of-00096.log](https://github.com/PacificBiosciences/HiFiTargetEnrichment/files/11984117/D18757.hs37d5.00009-of-00096.log)
 
This is more of an update as of now because i will be out of office till monday, but i wil try to review the logs in the weekend, and hopefully come up with something.

**Comment by jrharting** [comment]
It looks like the latest error is coming from tensorflow and/or nucleus, see the `.log` file:

`RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed`

Googling this error (briefly), I only see an older reference to this issue on Macs: https://github.com/google/nucleus/issues/32

I believe you said you were using linux, correct?

**Comment by Sami-St** [comment]
Yes i am on Linux.

**Comment by Sami-St** [comment]
I believe Nucleus is the error i am trying to solve it atm i keep you updated

**Comment by Sami-St** [comment]
Hey Everyone, quick update i didnt find the issue tbhi could be because Nucleus can only run with a specific tensorflow version but wenn pulling deepvariant both should be installed/ put on the version they need so i am kinda confused.
When i try deepvariant outside of the workflow with --help i get

```
 I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Runs all 3 steps to go from input DNA reads to output VCF/gVCF files.


This script currently provides the most common use cases and standard models.
If you want to access more flags that are available in `make_examples`,
`call_variants`, and `postprocess_variants`, you can also call them separately
using the binaries in the Docker image.

For more details, see:
https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-quick-start.md

flags:

/opt/deepvariant/bin/run_deepvariant.py:
  --call_variants_extra_args: A comma-separated list of flag_name=flag_value. "flag_name" has to be valid flags for call_variants.py. If the flag_value is
    boolean, it has to be flag_name=true or flag_name=false.
  --customized_model: Optional. A path to a model checkpoint to load for the `call_variants` step. If not set, the default for each --model_type will be used
  --[no]dry_run: Optional. If True, only prints out commands without executing them.
    (default: 'false')
  --intermediate_results_dir: Optional. If specified, this should be an existing directory that is visible insider docker, and will be used to to store
    intermediate outputs.
  --logging_dir: Optional. Directory where we should write log files for each stage and optionally runtime reports.
  --make_examples_extra_args: A comma-separated list of flag_name=flag_value. "flag_name" has to be valid flags for make_examples.py. If the flag_value is
    boolean, it has to be flag_name=true or flag_name=false.
  --model_type: <WGS|WES|PACBIO|HYBRID_PACBIO_ILLUMINA>: Required. Type of model to use for variant calling. Set this flag to use the default model
    associated with each type, and it will set necessary flags corresponding to each model. If you want to use a customized model, add --customized_model
    flag in addition to this flag.
  --num_shards: Optional. Number of shards for make_examples step.
    (default: '1')
    (an integer)
  --output_gvcf: Optional. Path where we should write gVCF file.
  --output_vcf: Required. Path where we should write VCF file.
  --postprocess_variants_extra_args: A comma-separated list of flag_name=flag_value. "flag_name" has to be valid flags for postprocess_variants.py. If the
    flag_value is boolean, it has to be flag_name=true or flag_name=false.
  --reads: Required. Aligned, sorted, indexed BAM file containing the reads we want to call. Should be aligned to a reference genome compatible with --ref.
  --ref: Required. Genome reference to use. Must have an associated FAI index as well. Supports text or gzipped references. Should match the reference used
    to align the BAM file provided to --reads.
  --regions: Optional. Space-separated list of regions we want to process. Elements can be region literals (e.g., chr20:10-20) or paths to BED/BEDPE files.
  --[no]runtime_report: Output make_examples runtime metrics and create a visual runtime report using runtime_by_region_vis. Only works with --logging_dir.
    (default: 'false')
  --sample_name: Sample name to use instead of the sample name from the input reads BAM (SM tag in the header). This flag is used for both make_examples and
    postprocess_variants.
  --[no]use_hp_information: (Deprecated in v1.4.0) Optional. If True, corresponding flags will be set to properly use the HP information present in the BAM
    input.
  --[no]vcf_stats_report: Optional. Output a visual report (HTML) of statistics about the output VCF.
    (default: 'true')
  --[no]version: Optional. If true, print out version number and exit.
```

so i believe its working.. in the next few days i will open a issue in the deepvariant repositorie and ask about that there.

Best Regards

**Comment by Sami-St** [comment]
Hello everyone,

so the Problem was acutally nucleus deepvariant will not use the version that come's with it in the container it rather uses the local version of nucleus and that was the Problem, now it works just fine. I am gonna close the Issue with this.

Thanks for the help and support.
Best regards 
Sami
